<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.2.0.0" ID="e1b3cb70-f7fc-4b62-b822-e5302d673356" Name="Junicsoft">
	<Dependencies>
		<SchemePartition ID="c0aa4f8e-0bb0-4a9e-93c7-88507423a84c" Name="Custom" />
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
	</Dependencies>
	<SchemeTable ID="177e70e5-4e7e-41a0-882d-87ea0417a931" Name="PersonalList" IsExternal="true" />
	<SchemeTable ID="56cc4eba-5c3c-41b5-afd1-deed95dc739f" Name="PersonalListRoles" IsExternal="true" />
	<SchemeTable ID="7a2dfe5c-b049-421c-b67f-93ad53355485" Name="PersonalListRolesVirtual" IsExternal="true" />
	<SchemeTable ID="4ba3d202-be30-4f4a-955d-2f8acd697c6f" Name="PersonalPartnerList" IsExternal="true" />
	<SchemeTable ID="ec645c2d-b316-489c-a300-d0ba41049707" Name="PersonalPartnerListEntry" IsExternal="true" />
	<SchemeTable ID="67febfaf-f5f5-4b3d-9363-8a5053c38d79" Name="SampleText" IsExternal="true" />
	<SchemeTable ID="4a5d1567-6e66-4057-83b3-c9eeb3248f42" Name="TaskTextTemplate" IsExternal="true" />
</SchemePartition>