<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.2.0.0" ID="cc57f9b4-e75d-4c83-a1da-b650fb8e8149" Name="AI">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
	</Dependencies>
	<SchemeTable ID="b184a102-c827-4950-a012-cfede4272867" Name="AiBaseFileKinds" IsExternal="true" />
	<SchemeTable ID="83e5f876-1537-45e8-a962-d7d7a8749bab" Name="AiBaseFileOperationStates" IsExternal="true" />
	<SchemeTable ID="3324df2e-6cbd-4e7a-bf9f-8f7762e3f83d" Name="AiBaseFiles" IsExternal="true" />
	<SchemeTable ID="c5bcb860-656c-40de-a599-9de51c1e766a" Name="AiBaseFileUpdates" IsExternal="true" />
	<SchemeTable ID="11ab6365-8c4b-487d-951b-5a932477cdab" Name="AiBaseVirtualFiles" IsExternal="true" />
	<SchemeTable ID="62ec8a40-5bc5-41b3-9e8a-9f2c52fc318a" Name="AiCacheInstance" IsExternal="true" />
	<SchemeTable ID="dad4ef24-8b08-41f7-b5ea-6f556f95bd2c" Name="AiDerivedFileKinds" IsExternal="true" />
	<SchemeTable ID="76bcb0f5-cd68-4655-b7fe-07c675d2ad3b" Name="AiDerivedFiles" IsExternal="true" />
	<SchemeTable ID="ede76637-d1de-4022-b479-69d8eca71232" Name="AiFileOperations" IsExternal="true" />
	<SchemeTable ID="fcfbb13c-0dbb-453a-80e9-3811b48ae5ae" Name="AiLooseFileHashes" IsExternal="true" />
	<SchemeTable ID="cd3b3d0e-85de-40ec-8fea-5f685a99e591" Name="AiModel" IsExternal="true" />
	<SchemeTable ID="36f8762c-1731-4682-bff3-696a8609bc42" Name="AiPromptTestFileKind" IsExternal="true" />
	<SchemeTable ID="0fd5a4f7-ce06-4250-9f9b-4760d334aadf" Name="AiPromptTestFiles" IsExternal="true" />
	<SchemeTable ID="c6c447cc-adc6-4ee5-bf1e-2c65537162e6" Name="AiPromptTestRequestStates" IsExternal="true" />
	<SchemeTable ID="91e83dd3-0932-404d-b744-fab67214777e" Name="AiPromptTests" IsExternal="true" />
	<SchemeTable ID="4fda8c4e-1b71-45f0-96f1-5c785cea7509" Name="AiTool" IsExternal="true" />
	<SchemeTable ID="78a63577-af61-494e-984a-b5c6ae2c3f71" Name="AiToolAction" IsExternal="true" />
	<SchemeTable ID="1be04a56-b91c-406f-b96c-fa13fda9ead8" Name="AiToolAdditionalInstructionKind" IsExternal="true" />
	<SchemeTable ID="9c6ca046-eec4-4fb8-be98-652788bbc64d" Name="AiToolAdditionalInstructions" IsExternal="true" />
	<SchemeTable ID="924e1a98-cdb4-49bb-9b83-2729cd787bea" Name="AiToolCollectionDisplayMethods" IsExternal="true" />
	<SchemeTable ID="54b30f43-f5ba-4748-af85-a891bb352352" Name="AiToolFieldMappings" IsExternal="true" />
	<SchemeTable ID="0e274b40-2e24-4315-ab1e-b63c46986179" Name="AiToolFilterParams" IsExternal="true" />
	<SchemeTable ID="9aa9fb54-ed55-4828-81fa-31e4b4e52833" Name="AiToolInfoCache" IsExternal="true" />
	<SchemeTable ID="e2b5dc2d-707d-452e-940c-29ddaabefc49" Name="AiToolMode" IsExternal="true" />
	<SchemeTable ID="0b8beefb-4da7-492c-b5d5-2864e2797f27" Name="AiToolProcessType" IsExternal="true" />
	<SchemeTable ID="251b7528-a0db-43f7-83c0-8fb0c45db41a" Name="AiToolSearchService" IsExternal="true" />
	<SchemeTable ID="6d6fc9b0-e7ca-4b61-9721-9830af32cd88" Name="AiToolSectionSettings" IsExternal="true" />
	<SchemeTable ID="1f850cc2-da8e-41a9-95da-b837e4cb6c5f" Name="AiToolViewColumns" IsExternal="true" />
	<SchemeTable ID="f1278826-59c5-4728-85a0-3d1907db4dc8" Name="AiToolVirtual" IsExternal="true" />
	<SchemeTable ID="b23fccd5-5ba1-45b6-a0ad-e9d0cf730da0" Name="OperationTypes" IsExternal="true" />
</SchemePartition>