import { ExtensionRegistrator } from '@tessa/application';
import { PlaygroundArticle$ } from 'tessa/ui/playground';
import { AutocompleteArticle } from './articles/autocompleteArticle';
import { ButtonArticle } from './articles/buttonArticle/buttonArticle';
import { CheckboxArticle } from './articles/checkboxArticle';
import { ColorPickerArticle } from './articles/colorPickerArticle';
import { DropdownArticle } from './articles/dropdownArticle';
import { GridColumnsArticle } from './articles/grid/gridColumnsArticle';
import { GridCreateArticle } from './articles/grid/gridCreateArticle';
import { GridCustomizationArticle } from './articles/grid/gridCustomizationArticle';
import { GridExamplesArticle } from './articles/grid/gridExamplesArticle';
import { GridPermissionsArticle } from './articles/grid/gridPermissionsArticle';
import { GridPropertyGridArticle } from './articles/grid/gridPropertyGridArticle';
import { GridSelectionArticle } from './articles/grid/gridSelectionArticle';
import { GridEditableCellsArticle } from './articles/grid/gridEditableCellsArticle';
import { GridSortArticle } from './articles/grid/gridSortArticle';
import { PropertyGridBasicArticle } from './articles/propertyGrid/propertyGridBasicArticle';
import { PropertyGridDisplayArticle } from './articles/propertyGrid/propertyGridDisplayArticle';
import { PropertyGridPropertiesArticle } from './articles/propertyGrid/propertyGridPropertiesArticle';
import { PropertyGridProvidersArticle } from './articles/propertyGrid/propertyGridProvidersArticle';
import { PropertyGridMiscellaneousArticle } from './articles/propertyGrid/propertyGridMiscellaneousArticle';
import { RichTextBoxControlsArticle } from './articles/richTextBox/richTextBoxControlsArticle';
import { RichTextBoxEditorsArticle } from './articles/richTextBox/richTextBoxEditorsArticle';
import { RichTextBoxFakeCardArticle } from './articles/richTextBox/richTextBoxFakeCardArticle';
import { RichTextBoxHtmlContentArticle } from './articles/richTextBox/richTextBoxIHtmlContentArticle';
import { RichTextBoxInterviewArticle } from './articles/richTextBox/richTextBoxInterviewArticle';
import { RichTextBoxLargeContentArticle } from './articles/richTextBox/richTextBoxLargeContentArticle';
import { RichTextBoxLegacyRichArticle } from './articles/richTextBox/richTextBoxLegacyRichArticle';
import { RichTextBoxMailArticle } from './articles/richTextBox/richTextBoxMailArticle';
import { RichTextBoxModesArticle } from './articles/richTextBox/richTextBoxModesArticle';
import { RichTextBoxPermissionsArticle } from './articles/richTextBox/richTextBoxPermissionsArticle';
import { RichTextBoxSerializationArticle } from './articles/richTextBox/richTextBoxSerializationArticle';
import { TextFieldArticle } from './articles/textFieldArticle';
import { UserInfoArticle } from './articles/userInfoArticle';
import { GridStressTestArticle } from './articles/grid/gridStressTestArticle';
import { GridRowsReorderArticle } from './articles/grid/gridRowsReorderArticle';
import { GridPanelsArticle } from './articles/grid/gridPanelsArticle';
import { GridSearchArticle } from './articles/grid/gridSearchArticle';
import { AlertArticle } from './articles/alertArticle/alertArticle';
import { GridRowsArticle } from './articles/grid/gridRowsArticle';
import { GridLayoutArticle } from './articles/grid/gridLayoutArticle';
import { TreeArticle } from './articles/tree/treeArticle';
import { WorkflowLayoutArticle } from './articles/workflow/workflowLayoutArticle';
import { WorkflowLayoutEditorArticle } from './articles/workflow/workflowLayoutEditorArticle';
import { IconsArticle } from './articles/icons/iconsArticle';
import { GridSettingsArticle } from './articles/grid/gridSettingsArticle';
import { TreeCustomArticle } from './articles/tree/treeCustomizationArticle';
import { TreeDragNDropArticle } from './articles/tree/treeDragNDropArticle';
import { TreeSelectionArticle } from './articles/tree/treeSelectionArticle';
import { TreePerformanceArticle } from './articles/tree/treePerformanceArticle';
import { MessengersArticle } from './articles/messengersArticle';
import { DatePickerArticle } from './articles/datePickerArticle';
import { ListArticle } from './articles/list/listArticle';
import { WorkflowEditorsArticle } from './articles/workflow/workflowEditorsArticle';
import { WorkflowActionEditorArticle } from './articles/workflow/workflowActionEditorArticle';
import { WorkflowBindingsArticle } from './articles/workflow/workflowBindingsArticle';
import { WorkflowParametrizedControlTestArticle } from './articles/workflow/workflowParametrizedControlTestArticle';
import { GridRowDetailsArticle } from './articles/grid/gridRowDetailsArticle';
import { WorkflowHashEditorArticle } from './articles/workflow/workflowHashEditorArticle';
import { ChipArticle } from './articles/chipArticle';
import { SliderArticle } from './articles/slider/sliderArticle';
import { GridExtensionsArticle } from './articles/grid/gridExtensionsArticle';
import { GridServerDataArticle } from './articles/grid/gridServerDataArticle';
import { GridPagingArticle } from './articles/grid/gridPagingArticle';

export const DefaultArticlesRegistrator: ExtensionRegistrator = {
  async registerTypes(container) {
    container.bind(PlaygroundArticle$).to(CheckboxArticle);
    container.bind(PlaygroundArticle$).to(ColorPickerArticle);
    container.bind(PlaygroundArticle$).to(TextFieldArticle);
    container.bind(PlaygroundArticle$).to(DatePickerArticle);
    container.bind(PlaygroundArticle$).to(AutocompleteArticle);
    container.bind(PlaygroundArticle$).to(DropdownArticle);
    container.bind(PlaygroundArticle$).to(UserInfoArticle);
    container.bind(PlaygroundArticle$).to(TreeArticle);
    container.bind(PlaygroundArticle$).to(TreeCustomArticle);
    container.bind(PlaygroundArticle$).to(TreeDragNDropArticle);
    container.bind(PlaygroundArticle$).to(TreeSelectionArticle);
    container.bind(PlaygroundArticle$).to(TreePerformanceArticle);
    container.bind(PlaygroundArticle$).to(PropertyGridBasicArticle);
    container.bind(PlaygroundArticle$).to(PropertyGridDisplayArticle);
    container.bind(PlaygroundArticle$).to(PropertyGridPropertiesArticle);
    container.bind(PlaygroundArticle$).to(PropertyGridProvidersArticle);
    container.bind(PlaygroundArticle$).to(PropertyGridMiscellaneousArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxControlsArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxEditorsArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxFakeCardArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxHtmlContentArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxInterviewArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxLargeContentArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxLegacyRichArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxMailArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxModesArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxPermissionsArticle);
    container.bind(PlaygroundArticle$).to(RichTextBoxSerializationArticle);
    container.bind(PlaygroundArticle$).to(ButtonArticle);
    container.bind(PlaygroundArticle$).to(WorkflowLayoutArticle);
    container.bind(PlaygroundArticle$).to(WorkflowActionEditorArticle);
    container.bind(PlaygroundArticle$).to(WorkflowParametrizedControlTestArticle);
    container.bind(PlaygroundArticle$).to(WorkflowLayoutEditorArticle);
    container.bind(PlaygroundArticle$).to(WorkflowEditorsArticle);
    container.bind(PlaygroundArticle$).to(WorkflowBindingsArticle);
    container.bind(PlaygroundArticle$).to(WorkflowHashEditorArticle);
    container.bind(PlaygroundArticle$).to(GridCreateArticle);
    container.bind(PlaygroundArticle$).to(GridExtensionsArticle);
    container.bind(PlaygroundArticle$).to(GridExamplesArticle);
    container.bind(PlaygroundArticle$).to(GridSelectionArticle);
    container.bind(PlaygroundArticle$).to(GridEditableCellsArticle);
    container.bind(PlaygroundArticle$).to(GridColumnsArticle);
    container.bind(PlaygroundArticle$).to(GridCustomizationArticle);
    container.bind(PlaygroundArticle$).to(GridPermissionsArticle);
    container.bind(PlaygroundArticle$).to(GridPanelsArticle);
    container.bind(PlaygroundArticle$).to(GridSortArticle);
    container.bind(PlaygroundArticle$).to(GridPagingArticle);
    container.bind(PlaygroundArticle$).to(GridRowsReorderArticle);
    container.bind(PlaygroundArticle$).to(GridSearchArticle);
    container.bind(PlaygroundArticle$).to(GridRowsArticle);
    container.bind(PlaygroundArticle$).to(GridRowDetailsArticle);
    container.bind(PlaygroundArticle$).to(GridLayoutArticle);
    container.bind(PlaygroundArticle$).to(GridSettingsArticle);
    container.bind(PlaygroundArticle$).to(GridPropertyGridArticle);
    container.bind(PlaygroundArticle$).to(GridStressTestArticle);
    container.bind(PlaygroundArticle$).to(GridServerDataArticle);
    container.bind(PlaygroundArticle$).to(AlertArticle);
    container.bind(PlaygroundArticle$).to(IconsArticle);
    container.bind(PlaygroundArticle$).to(MessengersArticle);
    container.bind(PlaygroundArticle$).to(ListArticle);
    container.bind(PlaygroundArticle$).to(ChipArticle);
    container.bind(PlaygroundArticle$).to(SliderArticle);
  }
};

export * from './articles/buttonArticle/buttonArticleRegistrator';
export * from './articles/richTextBox/richTextBoxArticleRegistrators';
export * from './articles/grid/gridArticleRegistrator';
