<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.2.0.0" ID="e365a9cd-cc76-4e88-a3c6-1b307e45db99" Name="ApprovalProcess">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
		<SchemePartition ID="dd8eeaba-9042-4fb5-9e8e-f7544463464f" Name="Workflow" />
	</Dependencies>
	<SchemeTable ID="26484dc5-6148-49a5-9010-f1dd0e46ba6d" Name="ApprovalProcessAction" IsExternal="true" />
	<SchemeTable ID="59f08c9a-1149-44d7-aa15-64f44917c16f" Name="ApprovalProcessActionApprovedLinks" IsExternal="true" />
	<SchemeTable ID="1a8788db-7279-420d-8976-b6d04a921d2b" Name="ApprovalProcessActionDisapprovedLinks" IsExternal="true" />
	<SchemeTable ID="19dfd8b9-a3dd-46e4-b686-51cf08bd6e01" Name="ApprovalProcessActionRevokedLinks" IsExternal="true" />
	<SchemeTable ID="7a791775-ad11-4b9b-a793-ed0cc0aaf29d" Name="ApprovalProcessControlAction" IsExternal="true" />
	<SchemeTable ID="31d12e30-acd4-4c46-87ba-0bc3fc4febe3" Name="ApprovalProcessControlMethods" IsExternal="true" />
	<SchemeTable ID="86bc6d2f-dce4-4382-ab7c-204bc9c0ec77" Name="ApprovalProcessControlTypes" IsExternal="true" />
	<SchemeTable ID="ab2ec272-eb83-429d-b4fc-155bb55f13dd" Name="ApprovalProcessInfo" IsExternal="true" />
	<SchemeTable ID="eac3013d-02ea-4a26-ab28-75af8ea61e4e" Name="ApprovalProcessInfoApprovers" IsExternal="true" />
	<SchemeTable ID="83f77ddf-94f8-4322-918f-151c32bf58b1" Name="ApprovalProcessInfoModes" IsExternal="true" />
	<SchemeTable ID="7f7dc925-15a3-4d93-b96c-4c6140ecc36f" Name="ApprovalProcessInfoTaskRoles" IsExternal="true" />
	<SchemeTable ID="b43c68d0-a317-4aad-a400-dda21b33aa29" Name="ApprovalProcessInfoTasks" IsExternal="true" />
	<SchemeTable ID="f5fcc2bd-e398-4170-a467-e23c587d8ee0" Name="ApprovalProcessInstanceNodes" IsExternal="true" />
	<SchemeTable ID="d3b547df-315d-4cda-a345-668428c3a14d" Name="ApprovalProcessInstances" IsExternal="true" />
	<SchemeTable ID="37d8cfe8-6b12-4b5e-a537-c77d7e168f4f" Name="ApprovalProcessSettings" IsExternal="true" />
	<SchemeTable ID="7845ed70-a6bc-4b62-8d3d-7a219df2f0fb" Name="ApprovalProcessStates" IsExternal="true" />
	<SchemeTable ID="5c209fc5-c16f-41af-bebc-1e125ebf3a4c" Name="ApprovalProcessTasks" IsExternal="true" />
	<SchemeTable ID="5cfc5ed0-ba1e-4068-8385-c2e7e8178a93" Name="ApprovalProcessTemplates" IsExternal="true" />
	<SchemeTable ID="191e5dcd-69a6-4ac0-8e1e-77a4224aba34" Name="ApprovalProcessTemplateTypes" IsExternal="true" />
	<SchemeTable ID="1a33e40c-bf9c-4506-bebd-45b9c20f8512" Name="ApprovalProcessTemplateUsers" IsExternal="true" />
	<SchemeTable ID="1d350f24-c25b-495c-9704-28e02a412631" Name="ApprovalProcessTemplateWriters" IsExternal="true" />
	<SchemeTable ID="53dc8c0b-391a-4fbd-86c0-3da697abf065" Name="WorkflowSignalTypes" IsExternal="true" />
</SchemePartition>