<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.2.0.0" ID="5c4efc57-f311-4292-9cb1-7be629984589" Name="AbTest">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
	</Dependencies>
	<SchemeTable ID="9cbc0f98-571a-4822-a290-3e36b2f2f2e6" Name="AbCarAdditionalInfo" IsExternal="true" />
	<SchemeTable ID="30295c44-c633-4474-9e30-4492e75e7e75" Name="AbCarCustomers" IsExternal="true" />
	<SchemeTable ID="509d961f-00cf-4403-a78f-6736841de448" Name="AbCarMainInfo" IsExternal="true" />
	<SchemeTable ID="2cff79c9-6e5a-4e98-8c8f-7a14eb7bec80" Name="AbCarOwners" IsExternal="true" />
	<SchemeTable ID="6dc3a829-b1f4-4e67-ba99-16a30fe91209" Name="AbCarSales" IsExternal="true" />
	<SchemeTable ID="7f813c98-3331-46a9-8aa0-bab55a956246" Name="AbCustomerOperations" IsExternal="true" />
	<SchemeTable ID="f3886f6b-24cc-421e-802f-73f0eda24d1d" Name="AbPerformers" IsExternal="true" />
	<SchemeTable ID="3e3bd0fb-1faf-4311-b26b-17f01c844fdb" Name="AbResolutions" IsExternal="true" />
	<SchemeTable ID="ae17aa42-0478-40af-9fde-1e075a388026" Name="AbResolutionStages" IsExternal="true" />
	<SchemeTable ID="08cf782d-4130-4377-8a49-3e201a05d496" Name="CompletionOptions" IsExternal="true" />
</SchemePartition>